### ISSUE TITLE
🛣️ 1.1.0 Roadmap — The great cleaning

### ISSUE THREAD

**Issue by tascord** [flo-output/FLComponents#6]
**Megathread for required tasks relating to 1.1.0**

## Synopsis
🎉 1.0.0 is done !!!  
Now we have to clean up it's mess.

## System Changes (Breaking)
- [x] Nothing described yet

## Component Changes
- [ ] Numerical input button messyness
- [ ] [Accessibility](https://github.com/flo-output/FLComponents/issues/4)
- [ ] [Image Component](https://github.com/flo-output/FLComponents/issues/5)
- [ ] AppShell
- [ ] Breadcrumbs
- [ ] Segmented Control
- [ ] Text Area
- [ ] Affix
- [ ] Modal
- [ ] Accordion
